"""
Bakes the home-screen LUDI wordmark (Anton 168px, letter-spacing 4px, centred in the
390px hero, line-height 1 at top 118) into an SVG path, so every platform draws the same
outline. Shaping goes through HarfBuzz so kerning matches the browser render of home.html.

    pip install fonttools uharfbuzz
    python3 scripts/wordmark-path.py > src/components/home/wordmarkPath.ts
"""
import math
import sys
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

TEXT = "LUDI"
SIZE = 168
TRACKING = 4
HERO_WIDTH = 390
TOP = 118

font_path = Path(__file__).resolve().parent.parent / "node_modules/@expo-google-fonts/anton/400Regular/Anton_400Regular.ttf"
font = TTFont(font_path)
upm = font["head"].unitsPerEm
scale = SIZE / upm
os2 = font["OS/2"]
ascent, descent = round(os2.sTypoAscender * scale), round(-os2.sTypoDescender * scale)
# Chrome floors the (negative) half-leading of a line-height:1 line box.
baseline = TOP + math.floor((SIZE - (ascent + descent)) / 2) + ascent

blob = hb.Blob(font_path.read_bytes())
hb_font = hb.Font(hb.Face(blob))
buf = hb.Buffer()
buf.add_str(TEXT)
buf.guess_segment_properties()
hb.shape(hb_font, buf, {"kern": True, "liga": True})

advances = [p.x_advance * scale + TRACKING for p in buf.glyph_positions]
x = (HERO_WIDTH - sum(advances)) / 2
glyph_set = font.getGlyphSet()
order = font.getGlyphOrder()
pen = SVGPathPen(glyph_set, lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
for info, pos, adv in zip(buf.glyph_infos, buf.glyph_positions, advances):
    gx = x + pos.x_offset * scale
    glyph_set[order[info.codepoint]].draw(TransformPen(pen, (scale, 0, 0, -scale, gx, baseline - pos.y_offset * scale)))
    x += adv

sys.stdout.write(
    "// Generated by scripts/wordmark-path.py. Do not edit by hand.\n"
    f"/** LUDI in Anton 168px, hero coordinates (390 wide, baseline y={baseline:.2f}). */\n"
    f"export const WORDMARK_PATH =\n  '{pen.getCommands()}';\n"
)
